openapi: 3.0.1
info:
  title: Grain Market Backend Core API
  description: This API serves as the core for the Grain Market application.
  version: 1.0.0
servers:
- url: /api
paths:
  /commodity:
    get:
      tags:
      - Commodity
      summary: The base commodities that are transacted within the Grain Market application.
      description: Return a list of all base commodities.
      operationId: controllers.commodity.getAll
      responses:
        200:
          description: It worked!  Expect a list of commodities.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    CommodityName:
                      type: string
                    CommodityType:
                      type: string
                    LastUpdated:
                      type: string
                      description: The last time this commodity was updated.
  /inventory/{commodityId}:
    get:
      tags:
      - Inventory
      summary: Return a summary of the inventory for a specific commodity.
      description: Return a summary of the inventory for a specific commodity.
      operationId: controllers.inventory.getCommodityInventory
      parameters:
      - name: commodityId
        in: path
        description: ID assocaited with the commodity.
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Contains the summary of inventory available at this request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Commodity:
                    type: object
                    properties:
                      CommodityName:
                        type: string
                      CommodityType:
                        type: string
                      LastUpdated:
                        type: string
                        description: The last time this commodity was updated.
                  ValidityTimestamp:
                    type: string
                  TotalQuantity:
                    type: integer
                    description: The total volume of this commodity not contracted.
                  PendingQuantity:
                    type: integer
                    description: The volume of this commodity bound under pending
                      contract bids.
        404:
          description: The commodity was unavailable or not found.
          content: {}
  /bid/{commodityId}/{quantity}:
    post:
      tags:
      - Bid
      summary: Attempts to post a bid for the specified quantity and commodity.
      description: Attempts to post a bid for the specified quantity and commodity.
      operationId: controllers.bid.postBid
      parameters:
      - name: commodityId
        in: path
        description: ID assocaited with the commodity.
        required: true
        schema:
          type: integer
      - name: quantity
        in: path
        description: Total volume of the commodity to commit to.
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Yay!  You've expressed interest in obtaining some stuff.
          content: {}
        409:
          description: The commodity is temporarily unavailable, try again in a few
            seconds.
          content: {}
        423:
          description: The commodity is temporarily unavailable, try again in a few
            seconds.
          content: {}
      security:
        - basic: []
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: helpers.authentication.validateToken
